# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'D:\2020S\Mobilev4.4\SampleApp\stvmobilewebstore\platforms\ios\StvMobileWebStore' do
	project 'D:\2020S\Mobilev4.4\SampleApp\stvmobilewebstore\platforms\ios\StvMobileWebStore.xcodeproj'

end
